### ISSUE TITLE
Funcionalidade Cargo - View

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#10]
- Na Tela de Consulta, o header da última coluna deve ser Ação, pois só tem uma ação;
- Sempre que possível, é recomendável validar campos na tela, usando mensagens do messages.properties. Ver a funcionalidade Feriado;
- Validação de tamanho deve contemplar o tamanho no banco;

**Comment by romatos17** [comment]
Validação de tamanho de acordo com o banco realizado
Na tela de Consulta já está com o titulo da coluna "Ação"

**Comment by romatos17** [comment]
Falta verificar como se utilizar o messages.properties passando parâmetros no xhtml.
