### ISSUE TITLE
Funcionalidade Projeto - View

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#11]
- Revisar formatação e identação de alguns métodos;
- Nome do método ObterGerentes() fora do padrão de nomenclatura Java;
- Não está utilizando mensagem do messages.properties no "requiredMessage";
- Métodos de uso interno deveriam ser "private", ex.: ObterGerentes() e validarProjeto();

**Comment by romatos17** [comment]
As funcionalidades de projeto foram desenvolvidas por Igor (isouzaa)
