### ISSUE TITLE
Funcionalidade Sistema - View

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#16]
- Revisar formatação e identação. Linhas em branco a mais e falta de linha em branco separando blocos lógicos;
- Método cadastrarSistema() sem tratamento de exceção;
- No método validarSistema(), ordem da validação incorreta, não valida vazio e mensagem errada;
- Refazer o método modoCadastrar(). Ver a funcionalidade Cargo;
- Atributos "listaLider", "listaProjeto" devem estar no plural (padrão);
- Métodos listarLideres() e listarProjeto() de uso interno "public";
- Atributos "listaLider" e "listaProjeto" repetidos nos 2 ManagedBean;
- Atributos para os Services não são "transient" e repetidos nos 2 ManagedBean;
- Comentários TODO esquecido no código;
- Coluna "Nome do Sistema" deveria ser somente "Nome";
- Labels dos campos faltando ":" no final;
- No cadastro, não está utilizando mensagem no messages.properties com "requiredMessage";
- No cadastro, o "maxlength" dos campos na tela devem ser iguais ao do banco;
- @SuppressWarnings("unused") desnecessário;
- @SuppressWarnings("serial") desnecessário;

**Comment by dsantana0** [comment]
As seguintes sinalizações seguem pendentes: 
- No cadastro, não está utilizando mensagem no messages.properties com "requiredMessage";
- Atributos "listaLider" e "listaProjeto" repetidos nos 2 ManagedBean;
