### ISSUE TITLE
Funcionalidade Sistema - Service

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#17]
- Comentários vazios e códigos comentados esquecidos;
- Revisar classe Sistema quanto a formatação;
- Métodos no geral com TODO e printStackTrace();
- Tratamento de exceção usando mensagens e parâmetros incorretamente;
- Entidade Sistema não tem usuário, e sim líder;
- Os campos "lider", "projeto", "nome" são obrigatórios;

**Comment by dsantana0** [comment]
As seguintes sinalizações seguem pendentes:
- Entidade Sistema não tem usuário, e sim líder;
  -Os campos "lider", "projeto", "nome" são obrigatórios;
