### ISSUE TITLE
Funcionalidade Usuário - View

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#19]
- Na Tela de Consulta, o header da última coluna deve ser Ação, pois só tem uma ação;
- Sempre que possível, é recomendável validar campos na tela, usando mensagens do messages.properties;
- Revisar o método validarUsuario(). Checar nulidade, obrigatoriedade, usar isEmpty(), checar o tamanha de acordo com o banco de dados. Campos obrigatórios: "Nome", "Login", "Senha", "Sindicato", "Cidade";
- Método obterCidadePorEstado() interno está "public";

**Comment by romatos17** [comment]
O método obterCidadePorEstado() está sendo utilizada na view em uma lista. É para alterar ela para private?

**Comment by romatos17** [comment]
Falta verificar como se utilizar o messages.properties passando parâmetros no xhtml.

**Comment by fabmarc** [comment]
Se o obterCidadePorEstado() está no XHTML, então está correto ser "public".

**Comment by romatos17** [comment]
Tudo Ok
