### ISSUE TITLE
Modelo de Breadcrumb

### ISSUE THREAD

**Issue by isouzaa** [fabmarc/SisHE#20]
Marconi solicitou que colocássemos Breadcrumb nas páginas, porém modificamos o visual, porque o Breadcrumb com tema original do primefaces não ficou agradável abaixo do Menu do Sistema.
Gostaria que olhasse nos dê aprovação para aplicar nas outras páginas do sistema.
atualmente o Breadcrumb está nas Páginas de Usuário (consultar e Cadastrar).

**Comment by isouzaa** [comment]
![breadcrumb](https://cloud.githubusercontent.com/assets/10419165/6305053/384c76e0-b907-11e4-8916-8181aabf9dd7.PNG)

**Comment by raphaelgalvao** [comment]
Boa tarde @isouzaa 

Pode ficar nesse exemplo e replicar para as demais telas.

**Comment by raphaelgalvao** [comment]
Sugiro apenas uma modificação nos labels do breadcrum.

Ao inves de ficar:
Consultar Usuario > Cadastrar Usuario
Deve Ficar:
Usuario > Cadastrar (para a tela de cadastro)
Usuario > Consultar (para a tela de consulta)
Usuario > Detalhar (para tela de detalhes)

Resumindo, podemos adotar o padrao:
Funcionalidade > Ação Tela
