### ISSUE TITLE
[SISHE] Tela Consultar Feriados - Pesquisa sem resultados

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#22]
Pré-condição: 
1- Ter feriados cadastrados no sistema com abrangência Estado;

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Administração", após no submenu acionar a opção "Feriado" e o subitem "Consultar";
3- Preencher o campo "Abrangência" na "Tela Consultar Feriado" com a opção de estado;
4- Acionar o botão "Pesquisar";
5- Erro: Não exibe os feriados cadastrados com abrangência Estado na grid(Imagem: defeito_017.jpeg).

Resultado obtido (Erro/defeito): 
Passo 5

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir na grid os resultados encontrados

![defeito_017](https://cloud.githubusercontent.com/assets/11196176/6391525/d7f3f5b4-bd95-11e4-8b4e-bff77d5c9862.jpg)

**Comment by isouzaa** [comment]
Resolvido.

**Comment by lcassis** [comment]
Resolvido.
