### ISSUE TITLE
[SISHE] Tela Cadastrar Sindicato - Erro ao salvar

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#23]
Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Administração", após no submenu acionar a opção "Sindicato" e o subitem "Cadastrar";
3- Preencher os campos obrigatórios;
4- Acionar o botão "Confirmar";
5- Erro: HTTP Status 500 -(Imagem: defeito_013.jpeg).

Resultado obtido (Erro/defeito): 
Passo 5

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Confirmar o cadastro do Sindicato.

![defeito_013](https://cloud.githubusercontent.com/assets/11196176/6391869/d0210404-bd99-11e4-8513-d6fdb9c07472.jpg)

**Comment by dsantana0** [comment]
O erro apontado foi corrigido hoje pela manhã e foi adicionado ao repositório. 
Por favor,atualize o projeto e execute a rotina novamente.

**Comment by lcassis** [comment]
Aqui ainda apresenta o erro, acabei de atualizar, fiz logout e o erro persiste.

**Comment by lcassis** [comment]
![defeito_019](https://cloud.githubusercontent.com/assets/11196176/6392151/6ac342a4-bd9c-11e4-9dc6-ed38b6d8b761.jpg)

**Comment by dsantana0** [comment]
A correção havia sido realizada mas o servidor não havia sido reiniciado.

**Comment by raphaelgalvao** [comment]
Bom dia Leonora,

É necessario fazer o push do codigo comitado. Parar o servidor e reestartar, irei ae te mostrar como faz.

**Comment by lcassis** [comment]
Bom dia Raphael,

Diego já me mostrou, ontem fui orientada pelo Igor que só precisava realizar o pull, na verdade esse erro foi encontrado ontem, mas hoje quando eu iniciei os testes realizei o pull e ainda estava com o erro. Após reestartar o servidor verifiquei que a correção havia sito feita.

**Comment by lcassis** [comment]
Resolvido.
