### ISSUE TITLE
[SISHE] Tela Consultar Feriado - Pesquisa não exibe abrangência de feriados locais

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#24]
Pré-condição: 
1- Ter feriados cadastrados no sistema com abrangência Estado.

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Administração", após no submenu acionar a opção "Feriado" e o subitem "Consultar";
3- Acionar o botão "Pesquisar";
4- Erro: Não exibe abrangência de feriados locais(Imagem: defeito_011.jpeg).

Resultado obtido (Erro/defeito): 
Passo 4.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir na grid os resultados encontrados com a abrangência do feriado.

![defeito_011](https://cloud.githubusercontent.com/assets/11196176/6392023/09f4e32a-bd9b-11e4-81ca-b8336c2ccfc1.jpg)

**Comment by isouzaa** [comment]
Resolvido.

**Comment by lcassis** [comment]
Resolvido.
