### ISSUE TITLE
[SISHE] Tela Consultar Solicitação - Pesquisa sem resultados com status Pendente

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#25]
Pré-condição: 
1- Ter solicitações cadastrados no sistema com status "Pendente";

Passos executados:
1- Logar com o perfil Líder Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Consultar";
3- Preencher o campo "Status" com a opção "Pendente";
4- Preencher o campo "Solicitante" com a opção "Desenvolvedor";
5- Preencher os demais campos;
6- Acionar o botão "Pesquisar";
7- Erro: Não exibe na grid as solicitações cadastradas com Status "Pendente" (Imagem: defeito_020.jpeg).

Resultado obtido (Erro/defeito): 
Passo 7.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir na grid as solicitações do desenvolvedor com Status "Pendente".

![defeito_020](https://cloud.githubusercontent.com/assets/11196176/6392491/e5bec1ce-bd9f-11e4-88b0-2a25d58d1875.jpg)

**Comment by isouzaa** [comment]
Resolvido, na verdade o Lider só pode filtrar as solicitações próprias dele. para evitar esse tipo de confusão, agora o campos de filtro só ficam habilitados ao selecionar o checkbox "Minhas Solicitações".

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull do codigo e gerar uma nova versao, para retestar.

Qualquer duvida, em fazer o procedimento, pode me procurar.

**Comment by lcassis** [comment]
Conforme conversa com os desenvolvedores, a tela vai ter o seguinte comportamento:
1. Os filtros de pesquisa ficaram habilitados independente do checkbox.

**Comment by isouzaa** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull do codigo e gerar uma nova versao, para retestar.

Qualquer duvida, em fazer o procedimento, pode me procurar.

**Comment by lcassis** [comment]
Resolvido.
