### ISSUE TITLE
[SISHE] Tela Consultar Solicitação - Pesquisa sem resultados 

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#27]
Pré-condição: 
1- Ter solicitações cadastradas no sistema.

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Consultar";
3- Selecionar a opção "Todas as Solicitações";
4- Acionar o botão "Pesquisar";
5- Erro: Não exibe na grid as solicitações cadastradas com outros status, só com Status "Aprovada"
Imagem: defeito_026.jpeg).

Resultado obtido (Erro/defeito): 
Passo 5.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir na grid todas as solicitações cadastradas no sistema, independente do status. 

![defeito_026](https://cloud.githubusercontent.com/assets/11196176/6394055/95989612-bdad-11e4-8b53-4c976f3d58bf.jpg)

**Comment by isouzaa** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull do codigo e gerar uma nova versao, para retestar.

Qualquer duvida, em fazer o procedimento, pode me procurar.

**Comment by lcassis** [comment]
Resolvido.
