### ISSUE TITLE
[SISHE] Tela Consultar Solicitação - Detalhes - Status da Solicitação não informado

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#28]
Pré-condição: 
1- Ter solicitações cadastradas no sistema.

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Consultar";
3- Acionar o botão "Pesquisar";
4- Acionar o ícone "Lupa" da coluna "Ação";
5- Erro: No pop-up "Detalhes" não informa o status da solicitação (Imagem: defeito_027.jpeg).

Observação: Erro aparece em todas as telas de solicitação.

Resultado obtido (Erro/defeito): 
Passo 5.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir no pop-up "Detalhes" o status da solicitação e quem á aprovou.

![defeito_027](https://cloud.githubusercontent.com/assets/11196176/6395023/70be6112-bdb4-11e4-8002-1bd88200851d.jpg)

**Comment by isouzaa** [comment]
Resolvido. Foi colocada a informação de Aprovado ou reprovado no dialog de detalhamento.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor gerar versao e retestar, se estiver OK, fechar.

Qualquer problema favor entrar em contato.

**Comment by lcassis** [comment]
Resolvido.
