### ISSUE TITLE
[SISHE] Tela Cadastrar Projeto - Campo Gerente não apresenta opções

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#29]
Pré-condição: 
1- Ter usuários com cargo Gerente cadastrados no sistema;

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Administração", após no submenu acionar a opção "Projeto" e o subitem "Cadastrar";
3- Preencher os campos;
4- Acionar o combo "Gerente";
5- Erro: Não exibe opções no combo "Gerente" (Imagem: defeito_028.jpeg).

Resultado obtido (Erro/defeito): 
Passo 5

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir gerentes cadastrados.

![defeito_028](https://cloud.githubusercontent.com/assets/11196176/6395555/b7ebc806-bdb7-11e4-8c99-60246f21d873.jpg)

**Comment by isouzaa** [comment]
Resolvido, na verdade só faltava uma mensagem para avisar que não existem Gerentes disponíveis para um novo projeto, porque o sistema foi modelado para que um usuário Gerente seja apenas gerente de um Projeto por vez, não era problema nos métodos que carregam a lista.

**Comment by lcassis** [comment]
Bom dia Igor! 

Segundo conversamos ontem você me passou que um usuário Gerente só pode ser gerente de um projeto, mas segundo o apontamento desse roteiro do Sishe, cada projeto tem o seu gerente, que também é usuário do sistema, porém um gerente pode gerenciar mais de um projeto. Um bom exemplo que afirma essa questão é a célula de testes, um líder tem mais de um projeto e o gerente gerencia mais de um projeto. Favor olhar o documento Banco-Horas-Historias.pdf

**Comment by raphaelgalvao** [comment]
Igor favor verificar.

**Comment by isouzaa** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer pull. gerar nova versao e retestar.

**Comment by lcassis** [comment]
Resolvido.
