### ISSUE TITLE
Funcionalidade Feriado - Service

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#3]
- Método remove() mencionando Cargo no tratamento de erro;
- Método remove() referência chave de mensagem inexistente;
- Método update() com tratamento de exceção incompleto;
- Existe necessidade da classe Feriado ser Comparable?
- Classe Feriado com método compareTo() vazio;

**Comment by isouzaa** [comment]
Realmente não havia necessidade de Feriado ser Comparable.
