### ISSUE TITLE
[SISHE] Tela Relatório - Não gera relatórios para meses com solicitações aprovadas

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#30]
Pré-condição: 
1- Ter solicitações solicitações aprovadas.

Passos executados:
1- Logar no sistema com os perfis "Desenvolvedor", "Líder" ou "Gerente";
2- Acionar a opção do Menu "Solicitação", após no submenu acionar a opção "Relatório";
3- Acionar no Combo Box "Mês";
5- Erro: Não exibe opções de meses com solicitações aprovadas no combo "Mês" (Imagem: defeito_029.jpeg).

Resultado obtido (Erro/defeito): 
Passo 3.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir meses com solicitações aprovadas.
![defeito_029](https://cloud.githubusercontent.com/assets/11196176/6412398/faa0df88-be61-11e4-9b08-3b28fd36986e.jpg)
.

**Comment by romatos17** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer pull, gerar versao e retestar.

Qualquer problema favor entrar em contato.

**Comment by lcassis** [comment]
Resolvido.
