### ISSUE TITLE
[SISHE] Saldo - Calculo de Horas Extras com erro.

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#31]
Pré-condição: 
1- Ter solicitações de horas cadastradas no domingo aprovadas pelo gerente no sistema;

Passos executados:
1- Logar com o perfil Líder;
2- Mover o cursor sobre o ícone do saldo de horas "Porco";
3- Erro: Horas contabilizadas com cálculo errado (Imagem: defeito_031.jpeg).

Resultado obtido (Erro/defeito): 
Passo 3.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Cálculo deve ser baseado na quantidade de solicitações aprovadas
O Banco de Horas é calculado da seguinte forma: Sábados a partir das 15:00, as horas trabalhadas são acrescidas em 100%. Domingos e/ou feriados, 100% também. Nos demais períodos, não têm adicionais (0%); o Em São Paulo, as horas trabalhadas aos domingos e/ou feriados serão creditadas no Banco de Horas com o acréscimo de 40%.

![defeito_031](https://cloud.githubusercontent.com/assets/11196176/6412466/edb2c056-be62-11e4-8923-ce01679268c5.jpg)

**Comment by romatos17** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull, gerar versao e retestar, se estiver OK, fechar.

Qualquer problema favor entrar em contato.

**Comment by romatos17** [comment]
Leonora,
Por fazer fazer o Pull, pois novas atualizações foram realizadas para quando a solicitação for realizada para um feriado cadastrado.

**Comment by lcassis** [comment]
Ok.

**Comment by lcassis** [comment]
O erro persiste e o resultado do cálculo permanece errado. A porcentagem do domingo ficou com 900%.

![defeito_044](https://cloud.githubusercontent.com/assets/11196176/6419478/4e8f2e9e-be9c-11e4-84f7-bbab154a99d0.jpg)

**Comment by lcassis** [comment]
Resolvido.
