### ISSUE TITLE
[SISHE] Dúvida - Aprovação de solicitação do Líder

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#32]
Nas solicitações de Horas Extras feitas pelo Gerente do projeto, as solicitações são aprovadas automaticamente, nas solicitações feitas pelo líder, quando ele consulta aparece na grid as solicitações feitas por ele com o status pendente e com os botões "Aprovar" e "Reprovar".

Dúvida: Por que o comportamento do líder é diferente do comportamento do gerente, porque é permitido ele aprovar as suas solicitações?! Não seria mais adequado que ao acionar a solicitação dele os botões "Aprovar" e "Reprovar" fossem desabilitados.

**Comment by isouzaa** [comment]
Para não ficar dúvidas, agora o botão de Aprovar / Reprovar só aparece na tela onde de fato o Líder e gerente podem executar tais ações.
![issue 32 e 33](https://cloud.githubusercontent.com/assets/10419165/6414053/8fc27c46-be73-11e4-9d82-8933107351c4.png)

**Comment by lcassis** [comment]
Resolvido.
