### ISSUE TITLE
[SISHE] Tela Consultar Solicitação - Links "Reprovar" e "Aprovar" 

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#33]
Pré-condição: 
1- Ter solicitações do líder cadastradas no sistema;

Passos executados:
1- Logar com o perfil Líder Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Consultar";
3- Acionar o Check Box "Minhas Solicitações";
4- Acionar o botão "Pesquisar";
5- Erro: Exibe o link "Aprovar" e "Reprovar" para as solicitações do Líder (Imagem: defeito_033.jpeg).

Resultado obtido (Erro/defeito): 
Passo 5.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Não exibir os links "Aprovar" e "Reprovar" ao selecionar as solicitações do Líder.

![defeito_033](https://cloud.githubusercontent.com/assets/11196176/6413746/2e466326-be71-11e4-85f9-ded5d97cd888.jpg)

**Comment by isouzaa** [comment]
Para não ficar dúvidas, agora o botão de Aprovar / Reprovar só aparece na tela onde de fato o Líder e gerente podem executar tais ações.
![issue 32 e 33](https://cloud.githubusercontent.com/assets/10419165/6414053/8fc27c46-be73-11e4-9d82-8933107351c4.png)

**Comment by lcassis** [comment]
Resolvido.
