### ISSUE TITLE
[SISHE] Tela Relatório - Não apresenta opção para gerar relatório do líder e desenvolvedores

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#34]
Pré-condição: 
1- Ter solicitações do usuário que deseja gerar relatório cadastradas no sistema;

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Relatório";
3- Acionar o Combo Box "Mês";
4- Acionar o Combo Box "Ano";
5- Erro: Não apresenta opções para o gerente gerar relatório para os líderes dos seus projetos e desenvolvedores(Imagem: defeito_034.jpeg).

Resultado obtido (Erro/defeito): 
Passo 5.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir opção do Gerente gerar Relatório para Líder e Desenvolvedor.

![defeito_034](https://cloud.githubusercontent.com/assets/11196176/6414157/254bf788-be74-11e4-9b59-e3dc14a76154.jpg)

**Comment by romatos17** [comment]
Leonora,

Esse comportamento não é considerado um bug, pois não foi solicitado no sistema (não sendo um requisito), mas está funcionalidade poderia ser classificada como melhorias futuras para o sistema.

**Comment by lcassis** [comment]
Conforme conversado com os desenvolvedores, os perfis Líder e Gerente, terão a opção de gerar relatório para os membros da sua equipe. Para o gerente será permitido gerar relatório para os líderes e desenvolvedores do projeto que o mesmo gerencia e os líderes para os desenvolvedores da sua equipe.

**Comment by romatos17** [comment]
Implementado.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o pull e verificar com o reteste.

**Comment by lcassis** [comment]
Resolvido.
