### ISSUE TITLE
[SISHE] Tela Consultar Solicitação - Detalhes - Tela com comportamentos diferentes

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#35]
Pré-condição: 
1- Ter solicitações de Horas Extras cadastradas no sistema;

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Consultar";
3- Marcar o Check Box "Todas as Solicitações";
4- Acionar o botão "Pesquisar";
5- Acionar o ícone "Visualizar Solicitação" da coluna "Ação";
5- Erro: No pop-up "Detalhes", nas solicitações feitas pelo líder exibe que foi aprovado pelo líder, sendo que solicitações feitas pelo líder deveria ser aprovadas automaticamente e já passadas para o Gerente aprovar. Não havendo necessidade de exibir que foi aprovado por líder.

Resultado obtido (Erro/defeito): 
Passo 5.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir apenas que a solicitação foi aprovada pelo Gerente.

![defeito_036](https://cloud.githubusercontent.com/assets/11196176/6416972/0039247e-be89-11e4-8f8a-31f697d63711.jpg)
![defeito_037](https://cloud.githubusercontent.com/assets/11196176/6416973/0058f876-be89-11e4-8bfc-80135f1f7e78.jpg)

**Comment by isouzaa** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull do codigo e gerar uma nova versao, para retestar.

Qualquer duvida, em fazer o procedimento, pode me procurar.

**Comment by lcassis** [comment]
Resolvido.
