### ISSUE TITLE
Tela Consultar Solicitação - Detalhes - Falta da descrição do campo "Status";

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#36]
Pré-condição: 
1- Ter solicitações de Horas Extras cadastradas no sistema;

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Consultar";
3- Marcar o Check Box "Todas as Solicitações";
4- Acionar o botão "Pesquisar";
5- Acionar o ícone "Visualizar Solicitação" da coluna "Ação";
6- Erro: No pop-up "Detalhes", todos os campos são descritos, exceto o campos "Status" (imagem: defeito_038);

Resultado obtido (Erro/defeito): 
Passo 5.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir todos os campos com as suas devidas informações.

![defeito_038](https://cloud.githubusercontent.com/assets/11196176/6417090/d3c47258-be89-11e4-8413-da148606f23e.jpg)

**Comment by isouzaa** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull do codigo e gerar uma nova versao, para retestar.

Qualquer duvida, em fazer o procedimento, pode me procurar.

**Comment by lcassis** [comment]
Resolvido.
