### ISSUE TITLE
[SISHE] Tela Cadastrar Regra - Não permite registro de regras com mesma faixa de tempo

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#37]
Pré-condição: 
1- O sindicato devera ter sido cadastrado no sistema;

Passos executados:
1- Logar com o perfil Gerente Teste;
2- Acionar a opção do Menu "Administração" e após no submenu acionar a opção "Sindicato" e o subitem "Consultar";
3- Selecionar o sindicato;
4- Acionar o link "Regra";
5- Acionar o botão "Cadastrar";
6- Preencher os campos;
7- Acionar o botão "Confirmar";
8- Erro: O sistema não permite o cadastro da regra, informa que já existe um registro nesta faixa de tempo. (imagem: defeito_041);

Resultado obtido (Erro/defeito): 
Passo 8.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Exibir todos os campos com as suas devidas informações.

![defeito_041](https://cloud.githubusercontent.com/assets/11196176/6418408/9ac0b476-be93-11e4-841e-3b7b7b7e3cd8.jpg)

**Comment by isouzaa** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull do codigo e gerar uma nova versao, para retestar.

Qualquer duvida, em fazer o procedimento, pode me procurar.

**Comment by lcassis** [comment]
Resolvido.
