### ISSUE TITLE
[SISHE] Tela Consultar Solicitação - Campo Solicitante sem uso

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#38]
Pré-condição: 
1- Ter solicitações cadastradas no sistema;

Passos executados:
1- Logar com o perfil Líder Teste;
2- Acionar a opção do Menu "Solicitação" e após no submenu acionar a opção "Consultar";
3- Selecionar o checkbox "Minhas solicitações";

Resultado obtido: 
Passo 3: Ao acionar o checkbox "Minhas Solicitações", o campo "Solicitante" é desnecessário.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Melhoria:
Bloquear o campo "Solicitante", quando o checkbox "Minhas Solicitações" for selecionado.

![defeito_043](https://cloud.githubusercontent.com/assets/11196176/6419055/e5c616e6-be98-11e4-8a50-366aa3c808c3.jpg)

**Comment by isouzaa** [comment]
Resolvido. 
O campo agora fica desabilitado enquanto a opção "Minhas Solicitações" não é marcado, porque o Lider só pode ver solicitações pendentes do próprio sistema, para que aprove ou reprove.

**Comment by raphaelgalvao** [comment]
Leonora,

Favor fazer o Pull do codigo e gerar uma nova versao, para retestar.

Qualquer duvida, em fazer o procedimento, pode me procurar.

**Comment by lcassis** [comment]
Resolvido.
