### ISSUE TITLE
[SISHE] Tela Cadastrar Regra - Tela apresenta botões cortados

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#39]
Pré-condição: 
1- Ter sindicatos cadastrados no sistema;

Passos executados:
1- Logar com o perfil Gerente;
2- Acionar o menu "Administração", após acionar o submenu "Sindicato" e acionar o subitem "Consultar";
3- Acionar o botão "Pesquisar";
4- Selecionar o sindicato que deseja cadastrar regra;
5- Acionar o link "Regra";
6- Acionar o link "Cadastrar";
7- Erro: A tela exibe botões cortados (Imagem: defeito_049.jpeg).

Resultado obtido (Erro/defeito): 
Passo 7.

*Ambiente: Desenvolvimento
*Browser: Google Chrome versão 40

Resultado esperado: 
Tela exibindo os botões inteiros com o zoom 100%.

![defeito_049](https://cloud.githubusercontent.com/assets/11196176/6440827/f3e338a2-c0bf-11e4-900a-7e147f798ad6.jpg)

**Comment by isouzaa** [comment]
Resolvido.

**Comment by raphaelgalvao** [comment]
Bom dia Leonora,

Favor fazer Pull.. gerar uma nova versao e retestar.

Qualquer problema favor entrar em contato.

**Comment by lcassis** [comment]
Resolvido.
