### ISSUE TITLE
[SISHE] Tela Cadastrar Sindicato - Limites de horas mensais positivas e negativas não atendem as condições do Sindicato 

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#40]
Conforme o documento Banco-Horas-Historias.pdf, no cômputo mensal, dependendo da CCT vigente de cada sindicato, um funcionário não deve ter X horas excedentes no Banco de Horas, tanto positivas como negativas. No sindicato da Bahia o limite de horas mensais positivas e negativas no Banco de Horas é de 55 horas; Em São Paulo, o limite vigente é de 50 horas positivas e 40 horas negativas. 

Dúvida: O sistema não trata esse limite de horas mensais positivas e negativas. O sistema deveria tratar esse limite de horas?

![defeito_050](https://cloud.githubusercontent.com/assets/11196176/6442175/a3007226-c0cc-11e4-9333-ebef563ddaad.jpg)

**Comment by dsantana0** [comment]
Leonoroa, tratamos desta questão com Marconi e ficou acordado que o usuário poderia cadastrar mesmo que o limite fosse/estivesse excedido, visto que, com a periodicidade dos acertos estes excessos seriam subtraídos.

**Comment by lcassis** [comment]
Diego, como ponto de melhorias futuras isso devera mudar, no cadastro de sindicatos deveria tratar esse limite mensal positivo e negativo e não impedir que o usuário cadastre as suas solicitações mesmo ultrapassando o limite já que é permitido, como isso foi acordado com os gestores, o sistema deveria ao menos alertar ao gerente que o recurso excedeu esse limite de horas e que deve compensar horas, para que o Banco de Horas dele não exceda o limite mensal permitido pela CCT vigente.

**Comment by dsantana0** [comment]
Ok.

**Comment by dsantana0** [comment]
Leonora, de acordo com as sinalizações realizadas e com o andamento do projeto, esta funcionalidade ficará como melhorias futuras.

**Comment by lcassis** [comment]
Certo.
