### ISSUE TITLE
[SISHE] Compensação de Horas - Realizar baixa de horas

### ISSUE THREAD

**Issue by lcassis** [fabmarc/SisHE#41]
No caso compensação de horas pelo líder/desenvolvedor e em casos de falta injustificada ou atraso.

Dúvida: Como o gerente realizará a baixa de horas, de que forma debitará do saldo do recurso as horas folgadas. Esse débito será feito manualmente ou futuramente será criado no sistema essa função?

**Comment by dsantana0** [comment]
Nós estivemos com esta mesma dúvida e consultamos Marconi para saber se seria implementado uma funcionalidade para debitar estas horas. Ficou acordado que a solicitação de folga seria realizada por meio do sistema mas o cronograma não contemplou esta atividade.

**Comment by dsantana0** [comment]
Leonora, esta funcionalidade será implementada posteriormente por que no cronograma recebido não houve atribuição de CH nem de responsável pela tarefa, vale ressaltar que esta funcionalidade foi decidida após algumas conversas com Marconi e posteriormente com o cliente.

**Comment by lcassis** [comment]
Certo.
