### ISSUE TITLE
Funcionalidade Sindicato - View

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#7]
- Revisar formatação e identação. Linhas em branco a mais e falta de linha em branco separando blocos lógicos;
- Comentários vazios e códigos comentados esquecidos;
- Método cadastrarSindicato() sem tratamento de exceção;
- Método beforeRemoveCliente() na funcionalidade Sindicato?
- No método verificarDescricao(), comparação de litetal String com operador "==" e não checa nulidade antes de operar;
- Métodos validarSindicato() e verificarDescricao(), nome do parâmetro é "sindicatoFiltro"?
- Refazer o método modoCadastrar(). Ver a funcionalidade Cargo;
- Atributos "listaEstado", "listaSindicato" devem estar no plural (padrão);
- Coluna "Nome do Sindicato" deveria ser somente "Nome";
- Campo "Sindicato" deveria ser "Nome";
- Não está utilizando mensagem no messages.properties com "requiredMessage";
- No cadastro, o "maxlength" dos campos na tela devem ser iguais ao do banco;

**Comment by dsantana0** [comment]
O item "Não está utilizando mensagem no messages.properties com 'requiredMessage' " encontra-se pendente;
