### ISSUE TITLE
Funcionalidade Sindicato - Service

### ISSUE THREAD

**Issue by fabmarc** [fabmarc/SisHE#8]
- Comentários vazios e códigos comentados esquecidos;
- Revisar classe Sindicato quanto a formatação e comentários;
- Métodos no geral sem tratamento de exceção com TODO e printStackTrace();
- Os campos "descricao", "estado", "limitePositivo", "limiteNegativo" são obrigatórios;

**Comment by dsantana0** [comment]
OK.
